import { Category, Product } from '@/types';

export const categoryTree: Category = {
  id: 'root',
  name: 'All Products',
  slug: 'all',
  children: [
    {
      id: 'vapes',
      name: 'Vapes',
      slug: 'vapes',
      description: 'Disposable and rechargeable vape devices',
      children: [
        {
          id: 'flavor',
          name: 'Flavor',
          slug: 'flavor',
          description: 'Choose your favorite flavor',
          children: [
            { id: 'watermelon', name: 'Watermelon', slug: 'watermelon', isLeaf: true, shape: 'circle', color: '#ef4444' },
            { id: 'strawberry', name: 'Strawberry', slug: 'strawberry', isLeaf: true, shape: 'medium-rect', color: '#ec4899' },
            { id: 'grape', name: 'Grape', slug: 'grape', isLeaf: true, shape: 'circle', color: '#8b5cf6' },
            { id: 'mango', name: 'Mango', slug: 'mango', isLeaf: true, shape: 'large-rect', color: '#f59e0b' },
            { id: 'blueberry', name: 'Blueberry', slug: 'blueberry', isLeaf: true, shape: 'small-rect', color: '#3b82f6' },
            { id: 'peach', name: 'Peach', slug: 'peach', isLeaf: true, shape: 'pill', color: '#f97316' },
            { id: 'mint', name: 'Mint', slug: 'mint', isLeaf: true, shape: 'circle', color: '#14b8a6' },
            { id: 'vanilla', name: 'Vanilla', slug: 'vanilla', isLeaf: true, shape: 'medium-rect', color: '#fbbf24' },
          ],
        },
        {
          id: 'hits',
          name: 'Hits',
          slug: 'hits',
          description: 'Number of puffs per device',
          children: [
            { id: 'hits-5000', name: '5,000 Hits', slug: '5000-hits', isLeaf: true, shape: 'small-rect', color: '#10b981' },
            { id: 'hits-10000', name: '10,000 Hits', slug: '10000-hits', isLeaf: true, shape: 'medium-rect', color: '#22c55e' },
            { id: 'hits-15000', name: '15,000 Hits', slug: '15000-hits', isLeaf: true, shape: 'large-rect', color: '#16a34a' },
            { id: 'hits-20000', name: '20,000 Hits', slug: '20000-hits', isLeaf: true, shape: 'circle', color: '#15803d' },
          ],
        },
        {
          id: 'brand',
          name: 'Brand',
          slug: 'brand',
          description: 'Popular vape brands',
          children: [
            { id: 'brand-elfbar', name: 'Elf Bar', slug: 'elfbar', isLeaf: true, shape: 'medium-rect', color: '#6366f1' },
            { id: 'brand-geekbar', name: 'Geek Bar', slug: 'geekbar', isLeaf: true, shape: 'pill', color: '#8b5cf6' },
            { id: 'brand-lostmary', name: 'Lost Mary', slug: 'lostmary', isLeaf: true, shape: 'circle', color: '#a855f7' },
            { id: 'brand-funky republic', name: 'Funky Republic', slug: 'funky-republic', isLeaf: true, shape: 'large-rect', color: '#d946ef' },
            { id: 'brand-hyde', name: 'Hyde', slug: 'hyde', isLeaf: true, shape: 'small-rect', color: '#c026d3' },
          ],
        },
        {
          id: 'color',
          name: 'Color',
          slug: 'color',
          description: 'Device colors',
          children: [
            { id: 'color-red', name: 'Red', slug: 'red', isLeaf: true, shape: 'circle', color: '#ef4444' },
            { id: 'color-blue', name: 'Blue', slug: 'blue', isLeaf: true, shape: 'circle', color: '#3b82f6' },
            { id: 'color-black', name: 'Black', slug: 'black', isLeaf: true, shape: 'medium-rect', color: '#1f2937' },
            { id: 'color-pink', name: 'Pink', slug: 'pink', isLeaf: true, shape: 'pill', color: '#ec4899' },
            { id: 'color-teal', name: 'Teal', slug: 'teal', isLeaf: true, shape: 'circle', color: '#14b8a6' },
          ],
        },
        {
          id: 'sale',
          name: 'On Sale',
          slug: 'sale',
          description: 'Discounted items',
          isLeaf: true,
          shape: 'large-rect',
          color: '#f59e0b',
        },
      ],
    },
    {
      id: 'e-liquid',
      name: 'E-Liquid',
      slug: 'e-liquid',
      description: 'Vape juice and refills',
      children: [
        {
          id: 'eliquid-flavor',
          name: 'Flavor',
          slug: 'eliquid-flavor',
          children: [
            { id: 'eliquid-fruity', name: 'Fruity', slug: 'fruity', isLeaf: true, shape: 'medium-rect', color: '#f97316' },
            { id: 'eliquid-dessert', name: 'Dessert', slug: 'dessert', isLeaf: true, shape: 'circle', color: '#fbbf24' },
            { id: 'eliquid-menthol', name: 'Menthol', slug: 'menthol', isLeaf: true, shape: 'small-rect', color: '#06b6d4' },
            { id: 'eliquid-tobacco', name: 'Tobacco', slug: 'tobacco', isLeaf: true, shape: 'pill', color: '#78716c' },
          ],
        },
        {
          id: 'nicotine-strength',
          name: 'Nicotine Strength',
          slug: 'nicotine-strength',
          children: [
            { id: 'nic-0mg', name: '0mg (Nicotine Free)', slug: '0mg', isLeaf: true, shape: 'small-rect', color: '#22c55e' },
            { id: 'nic-3mg', name: '3mg', slug: '3mg', isLeaf: true, shape: 'circle', color: '#84cc16' },
            { id: 'nic-6mg', name: '6mg', slug: '6mg', isLeaf: true, shape: 'medium-rect', color: '#eab308' },
            { id: 'nic-12mg', name: '12mg', slug: '12mg', isLeaf: true, shape: 'pill', color: '#f59e0b' },
            { id: 'nic-18mg', name: '18mg', slug: '18mg', isLeaf: true, shape: 'large-rect', color: '#ef4444' },
          ],
        },
      ],
    },
    {
      id: 'accessories',
      name: 'Accessories',
      slug: 'accessories',
      description: 'Chargers, cases, and more',
      children: [
        { id: 'chargers', name: 'Chargers', slug: 'chargers', isLeaf: true, shape: 'medium-rect', color: '#3b82f6' },
        { id: 'cases', name: 'Cases', slug: 'cases', isLeaf: true, shape: 'pill', color: '#6366f1' },
        { id: 'lanyards', name: 'Lanyards', slug: 'lanyards', isLeaf: true, shape: 'small-rect', color: '#8b5cf6' },
        { id: 'cartridges', name: 'Cartridges', slug: 'cartridges', isLeaf: true, shape: 'circle', color: '#a855f7' },
      ],
    },
  ],
};

// Helper function to find a category by ID
export function findCategoryById(category: Category, id: string): Category | null {
  if (category.id === id) return category;
  if (category.children) {
    for (const child of category.children) {
      const found = findCategoryById(child, id);
      if (found) return found;
    }
  }
  return null;
}

// Helper function to get breadcrumb path
export function getCategoryPath(category: Category, targetId: string, path: Category[] = []): Category[] | null {
  if (category.id === targetId) return [...path, category];
  if (category.children) {
    for (const child of category.children) {
      const result = getCategoryPath(child, targetId, [...path, category]);
      if (result) return result;
    }
  }
  return null;
}

// Helper to check if a category has children
export function hasChildren(category: Category): boolean {
  return !!(category.children && category.children.length > 0);
}

// Mock Product Data
export const products: Product[] = [
  // Elf Bar Products
  {
    id: 'elfbar-watermelon-5000',
    name: 'Elf Bar Watermelon Ice 5000',
    description: 'Refreshing watermelon flavor with a cool icy finish. 5000 puffs of pure satisfaction.',
    price: 12.99,
    imageUrl: 'https://placehold.co/300x300/ef4444/white?text=Elf+Bar',
    categoryPath: ['vapes', 'flavor', 'watermelon', 'hits', 'hits-5000', 'brand', 'brand-elfbar'],
    brand: 'Elf Bar',
    flavor: 'watermelon',
    hits: 5000,
    color: 'Red',
    inStock: true,
  },
  {
    id: 'elfbar-strawberry-10000',
    name: 'Elf Bar Strawberry Banana 10000',
    description: 'Sweet strawberry blended with creamy banana. Double the puffs, double the flavor.',
    price: 19.99,
    imageUrl: 'https://placehold.co/300x300/ec4899/white?text=Elf+Bar',
    categoryPath: ['vapes', 'flavor', 'strawberry', 'hits', 'hits-10000', 'brand', 'brand-elfbar'],
    brand: 'Elf Bar',
    flavor: 'strawberry',
    hits: 10000,
    color: 'Pink',
    inStock: true,
  },
  {
    id: 'elfbar-grape-15000',
    name: 'Elf Bar Grape Energy 15000',
    description: 'Bold grape flavor with an energy drink twist. Long-lasting 15000 hit device.',
    price: 21.99,
    imageUrl: 'https://placehold.co/300x300/8b5cf6/white?text=Elf+Bar',
    categoryPath: ['vapes', 'flavor', 'grape', 'hits', 'hits-15000', 'brand', 'brand-elfbar', 'sale'],
    brand: 'Elf Bar',
    flavor: 'grape',
    hits: 15000,
    color: 'Purple',
    inStock: true,
  },
  {
    id: 'elfbar-mango-20000',
    name: 'Elf Bar Mango Peach 20000',
    description: 'Tropical mango meets juicy peach in our longest-lasting device.',
    price: 29.99,
    imageUrl: 'https://placehold.co/300x300/f59e0b/white?text=Elf+Bar',
    categoryPath: ['vapes', 'flavor', 'mango', 'hits', 'hits-20000', 'brand', 'brand-elfbar'],
    brand: 'Elf Bar',
    flavor: 'mango',
    hits: 20000,
    color: 'Orange',
    inStock: false,
  },
  {
    id: 'elfbar-blueberry-5000',
    name: 'Elf Bar Blueberry Raspberry 5000',
    description: 'Berry bliss with blueberry and raspberry fusion. Compact and powerful.',
    price: 14.99,
    imageUrl: 'https://placehold.co/300x300/3b82f6/white?text=Elf+Bar',
    categoryPath: ['vapes', 'flavor', 'blueberry', 'hits', 'hits-5000', 'brand', 'brand-elfbar'],
    brand: 'Elf Bar',
    flavor: 'blueberry',
    hits: 5000,
    color: 'Blue',
    inStock: true,
  },
  {
    id: 'elfbar-peach-10000',
    name: 'Elf Bar Peach Ice 10000',
    description: 'Juicy peach with a refreshing menthol kick. Perfect for all-day vaping.',
    price: 16.99,
    imageUrl: 'https://placehold.co/300x300/f97316/white?text=Elf+Bar',
    categoryPath: ['vapes', 'flavor', 'peach', 'hits', 'hits-10000', 'brand', 'brand-elfbar', 'sale'],
    brand: 'Elf Bar',
    flavor: 'peach',
    hits: 10000,
    color: 'Orange',
    inStock: true,
  },
  {
    id: 'elfbar-mint-5000',
    name: 'Elf Bar Cool Mint 5000',
    description: 'Crisp, clean mint flavor for a refreshing vape experience.',
    price: 14.99,
    imageUrl: 'https://placehold.co/300x300/14b8a6/white?text=Elf+Bar',
    categoryPath: ['vapes', 'flavor', 'mint', 'hits', 'hits-5000', 'brand', 'brand-elfbar'],
    brand: 'Elf Bar',
    flavor: 'mint',
    hits: 5000,
    color: 'Teal',
    inStock: true,
  },

  // Geek Bar Products
  {
    id: 'geekbar-vanilla-10000',
    name: 'Geek Bar Vanilla Cream 10000',
    description: 'Smooth vanilla custard flavor in a sleek device. Dessert lovers rejoice.',
    price: 18.99,
    imageUrl: 'https://placehold.co/300x300/fbbf24/white?text=Geek+Bar',
    categoryPath: ['vapes', 'flavor', 'vanilla', 'hits', 'hits-10000', 'brand', 'brand-geekbar'],
    brand: 'Geek Bar',
    flavor: 'vanilla',
    hits: 10000,
    color: 'Yellow',
    inStock: true,
  },
  {
    id: 'geekbar-watermelon-15000',
    name: 'Geek Bar Watermelon Bubblegum 15000',
    description: 'Sweet watermelon bubblegum flavor that lasts and lasts.',
    price: 19.99,
    imageUrl: 'https://placehold.co/300x300/ef4444/white?text=Geek+Bar',
    categoryPath: ['vapes', 'flavor', 'watermelon', 'hits', 'hits-15000', 'brand', 'brand-geekbar', 'sale'],
    brand: 'Geek Bar',
    flavor: 'watermelon',
    hits: 15000,
    color: 'Red',
    inStock: true,
  },
  {
    id: 'geekbar-mango-5000',
    name: 'Geek Bar Mango Ice 5000',
    description: 'Tropical mango with an icy exhale. Compact size, big flavor.',
    price: 13.99,
    imageUrl: 'https://placehold.co/300x300/f59e0b/white?text=Geek+Bar',
    categoryPath: ['vapes', 'flavor', 'mango', 'hits', 'hits-5000', 'brand', 'brand-geekbar'],
    brand: 'Geek Bar',
    flavor: 'mango',
    hits: 5000,
    color: 'Orange',
    inStock: false,
  },
  {
    id: 'geekbar-grape-20000',
    name: 'Geek Bar Grape Ice 20000',
    description: 'Bold grape flavor with cooling menthol. Our longest-lasting Geek Bar.',
    price: 28.99,
    imageUrl: 'https://placehold.co/300x300/8b5cf6/white?text=Geek+Bar',
    categoryPath: ['vapes', 'flavor', 'grape', 'hits', 'hits-20000', 'brand', 'brand-geekbar'],
    brand: 'Geek Bar',
    flavor: 'grape',
    hits: 20000,
    color: 'Purple',
    inStock: true,
  },
  {
    id: 'geekbar-strawberry-10000',
    name: 'Geek Bar Strawberry Kiwi 10000',
    description: 'Sweet strawberry balanced with tart kiwi. A perfect fruit blend.',
    price: 18.99,
    imageUrl: 'https://placehold.co/300x300/ec4899/white?text=Geek+Bar',
    categoryPath: ['vapes', 'flavor', 'strawberry', 'hits', 'hits-10000', 'brand', 'brand-geekbar'],
    brand: 'Geek Bar',
    flavor: 'strawberry',
    hits: 10000,
    color: 'Pink',
    inStock: true,
  },

  // Lost Mary Products
  {
    id: 'lostmary-blueberry-5000',
    name: 'Lost Mary Blueberry Ice 5000',
    description: 'Blueberry with a cool menthol finish. Compact and stylish design.',
    price: 15.99,
    imageUrl: 'https://placehold.co/300x300/3b82f6/white?text=Lost+Mary',
    categoryPath: ['vapes', 'flavor', 'blueberry', 'hits', 'hits-5000', 'brand', 'brand-lostmary'],
    brand: 'Lost Mary',
    flavor: 'blueberry',
    hits: 5000,
    color: 'Blue',
    inStock: true,
  },
  {
    id: 'lostmary-mint-10000',
    name: 'Lost Mary Spearmint 10000',
    description: 'Classic spearmint flavor for a clean, fresh vape.',
    price: 17.99,
    imageUrl: 'https://placehold.co/300x300/14b8a6/white?text=Lost+Mary',
    categoryPath: ['vapes', 'flavor', 'mint', 'hits', 'hits-10000', 'brand', 'brand-lostmary', 'sale'],
    brand: 'Lost Mary',
    flavor: 'mint',
    hits: 10000,
    color: 'Teal',
    inStock: true,
  },
  {
    id: 'lostmary-peach-15000',
    name: 'Lost Mary Peach Mango 15000',
    description: 'Exotic peach and mango blend. Long-lasting tropical escape.',
    price: 25.99,
    imageUrl: 'https://placehold.co/300x300/f97316/white?text=Lost+Mary',
    categoryPath: ['vapes', 'flavor', 'peach', 'hits', 'hits-15000', 'brand', 'brand-lostmary'],
    brand: 'Lost Mary',
    flavor: 'peach',
    hits: 15000,
    color: 'Orange',
    inStock: true,
  },
  {
    id: 'lostmary-vanilla-20000',
    name: 'Lost Mary Vanilla Tobacco 20000',
    description: 'Smooth vanilla with rich tobacco notes. For the sophisticated vaper.',
    price: 30.99,
    imageUrl: 'https://placehold.co/300x300/fbbf24/white?text=Lost+Mary',
    categoryPath: ['vapes', 'flavor', 'vanilla', 'hits', 'hits-20000', 'brand', 'brand-lostmary'],
    brand: 'Lost Mary',
    flavor: 'vanilla',
    hits: 20000,
    color: 'Yellow',
    inStock: false,
  },
  {
    id: 'lostmary-strawberry-5000',
    name: 'Lost Mary Strawberry Ice 5000',
    description: 'Fresh strawberry with icy menthol. Pocket-friendly size.',
    price: 15.99,
    imageUrl: 'https://placehold.co/300x300/ec4899/white?text=Lost+Mary',
    categoryPath: ['vapes', 'flavor', 'strawberry', 'hits', 'hits-5000', 'brand', 'brand-lostmary'],
    brand: 'Lost Mary',
    flavor: 'strawberry',
    hits: 5000,
    color: 'Pink',
    inStock: true,
  },

  // Funky Republic Products
  {
    id: 'funky-watermelon-20000',
    name: 'Funky Republic Watermelon Nana 20000',
    description: 'Watermelon and banana fusion with massive 20000 puff capacity.',
    price: 24.99,
    imageUrl: 'https://placehold.co/300x300/ef4444/white?text=Funky+Republic',
    categoryPath: ['vapes', 'flavor', 'watermelon', 'hits', 'hits-20000', 'brand', 'brand-funky+republic', 'sale'],
    brand: 'Funky Republic',
    flavor: 'watermelon',
    hits: 20000,
    color: 'Red',
    inStock: true,
  },
  {
    id: 'funky-grape-10000',
    name: 'Funky Republic Grape Soda 10000',
    description: 'Fizzy grape soda flavor that satisfies your sweet tooth.',
    price: 22.99,
    imageUrl: 'https://placehold.co/300x300/8b5cf6/white?text=Funky+Republic',
    categoryPath: ['vapes', 'flavor', 'grape', 'hits', 'hits-10000', 'brand', 'brand-funky+republic'],
    brand: 'Funky Republic',
    flavor: 'grape',
    hits: 10000,
    color: 'Purple',
    inStock: true,
  },
  {
    id: 'funky-mango-15000',
    name: 'Funky Republic Tropical Mango 15000',
    description: 'Pure tropical mango bliss. Escape to the islands with every puff.',
    price: 25.99,
    imageUrl: 'https://placehold.co/300x300/f59e0b/white?text=Funky+Republic',
    categoryPath: ['vapes', 'flavor', 'mango', 'hits', 'hits-15000', 'brand', 'brand-funky+republic'],
    brand: 'Funky Republic',
    flavor: 'mango',
    hits: 15000,
    color: 'Orange',
    inStock: false,
  },
  {
    id: 'funky-mint-5000',
    name: 'Funky Republic Arctic Mint 5000',
    description: 'Extreme menthol blast for mint lovers. Refreshing and bold.',
    price: 13.99,
    imageUrl: 'https://placehold.co/300x300/14b8a6/white?text=Funky+Republic',
    categoryPath: ['vapes', 'flavor', 'mint', 'hits', 'hits-5000', 'brand', 'brand-funky+republic', 'sale'],
    brand: 'Funky Republic',
    flavor: 'mint',
    hits: 5000,
    color: 'Teal',
    inStock: true,
  },
  {
    id: 'funky-blueberry-10000',
    name: 'Funky Republic Blueberry Lemon 10000',
    description: 'Tart lemon and sweet blueberry combine for a zesty vape.',
    price: 22.99,
    imageUrl: 'https://placehold.co/300x300/3b82f6/white?text=Funky+Republic',
    categoryPath: ['vapes', 'flavor', 'blueberry', 'hits', 'hits-10000', 'brand', 'brand-funky+republic'],
    brand: 'Funky Republic',
    flavor: 'blueberry',
    hits: 10000,
    color: 'Blue',
    inStock: true,
  },

  // Hyde Products
  {
    id: 'hyde-vanilla-5000',
    name: 'Hyde Vanilla Custard 5000',
    description: 'Rich vanilla custard dessert flavor. Creamy and satisfying.',
    price: 13.99,
    imageUrl: 'https://placehold.co/300x300/fbbf24/white?text=Hyde',
    categoryPath: ['vapes', 'flavor', 'vanilla', 'hits', 'hits-5000', 'brand', 'brand-hyde'],
    brand: 'Hyde',
    flavor: 'vanilla',
    hits: 5000,
    color: 'Yellow',
    inStock: true,
  },
  {
    id: 'hyde-peach-10000',
    name: 'Hyde Peach Blossom 10000',
    description: 'Delicate peach flavor with floral undertones. Elegant and smooth.',
    price: 17.99,
    imageUrl: 'https://placehold.co/300x300/f97316/white?text=Hyde',
    categoryPath: ['vapes', 'flavor', 'peach', 'hits', 'hits-10000', 'brand', 'brand-hyde'],
    brand: 'Hyde',
    flavor: 'peach',
    hits: 10000,
    color: 'Orange',
    inStock: true,
  },
  {
    id: 'hyde-strawberry-15000',
    name: 'Hyde Strawberry Cheesecake 15000',
    description: 'Decadent strawberry cheesecake in vape form. Dessert heaven.',
    price: 18.99,
    imageUrl: 'https://placehold.co/300x300/ec4899/white?text=Hyde',
    categoryPath: ['vapes', 'flavor', 'strawberry', 'hits', 'hits-15000', 'brand', 'brand-hyde', 'sale'],
    brand: 'Hyde',
    flavor: 'strawberry',
    hits: 15000,
    color: 'Pink',
    inStock: true,
  },
  {
    id: 'hyde-mint-20000',
    name: 'Hyde Icy Mint 20000',
    description: 'Intense menthol mint for a powerful cooling sensation.',
    price: 26.99,
    imageUrl: 'https://placehold.co/300x300/14b8a6/white?text=Hyde',
    categoryPath: ['vapes', 'flavor', 'mint', 'hits', 'hits-20000', 'brand', 'brand-hyde'],
    brand: 'Hyde',
    flavor: 'mint',
    hits: 20000,
    color: 'Teal',
    inStock: false,
  },
  {
    id: 'hyde-grape-5000',
    name: 'Hyde Grape Aloe 5000',
    description: 'Unique grape and aloe vera blend. Soothing and flavorful.',
    price: 13.99,
    imageUrl: 'https://placehold.co/300x300/8b5cf6/white?text=Hyde',
    categoryPath: ['vapes', 'flavor', 'grape', 'hits', 'hits-5000', 'brand', 'brand-hyde'],
    brand: 'Hyde',
    flavor: 'grape',
    hits: 5000,
    color: 'Purple',
    inStock: true,
  },

  // E-Liquid Products
  {
    id: 'eliquid-fruity-mix-3mg',
    name: 'Vape Juice Fruity Mix 3mg',
    description: 'A blend of tropical fruits with 3mg nicotine. 60ml bottle.',
    price: 24.99,
    imageUrl: 'https://placehold.co/300x300/f97316/white?text=E-Liquid',
    categoryPath: ['e-liquid', 'eliquid-flavor', 'eliquid-fruity', 'nicotine-strength', 'nic-3mg'],
    flavor: 'fruity',
    color: 'Orange',
    inStock: true,
  },
  {
    id: 'eliquid-berry-blast-6mg',
    name: 'Vape Juice Berry Blast 6mg',
    description: 'Mixed berry explosion with 6mg nicotine strength.',
    price: 19.99,
    imageUrl: 'https://placehold.co/300x300/3b82f6/white?text=E-Liquid',
    categoryPath: ['e-liquid', 'eliquid-flavor', 'eliquid-fruity', 'nicotine-strength', 'nic-6mg', 'sale'],
    flavor: 'fruity',
    color: 'Blue',
    inStock: true,
  },
  {
    id: 'eliquid-vanilla-custard-0mg',
    name: 'Vape Juice Vanilla Custard 0mg',
    description: 'Creamy vanilla custard, nicotine-free. Perfect for flavor chasers.',
    price: 26.99,
    imageUrl: 'https://placehold.co/300x300/fbbf24/white?text=E-Liquid',
    categoryPath: ['e-liquid', 'eliquid-flavor', 'eliquid-dessert', 'nicotine-strength', 'nic-0mg'],
    flavor: 'dessert',
    color: 'Yellow',
    inStock: true,
  },
  {
    id: 'eliquid-chocolate-donut-12mg',
    name: 'Vape Juice Chocolate Donut 12mg',
    description: 'Rich chocolate donut flavor with 12mg nicotine.',
    price: 27.99,
    imageUrl: 'https://placehold.co/300x300/fbbf24/white?text=E-Liquid',
    categoryPath: ['e-liquid', 'eliquid-flavor', 'eliquid-dessert', 'nicotine-strength', 'nic-12mg'],
    flavor: 'dessert',
    color: 'Brown',
    inStock: false,
  },
  {
    id: 'eliquid-menthol-ice-6mg',
    name: 'Vape Juice Menthol Ice 6mg',
    description: 'Pure menthol blast with 6mg nicotine. Maximum freshness.',
    price: 23.99,
    imageUrl: 'https://placehold.co/300x300/06b6d4/white?text=E-Liquid',
    categoryPath: ['e-liquid', 'eliquid-flavor', 'eliquid-menthol', 'nicotine-strength', 'nic-6mg'],
    flavor: 'menthol',
    color: 'Cyan',
    inStock: true,
  },
  {
    id: 'eliquid-spearmint-3mg',
    name: 'Vape Juice Spearmint 3mg',
    description: 'Classic spearmint flavor with mild 3mg nicotine.',
    price: 20.99,
    imageUrl: 'https://placehold.co/300x300/14b8a6/white?text=E-Liquid',
    categoryPath: ['e-liquid', 'eliquid-flavor', 'eliquid-menthol', 'nicotine-strength', 'nic-3mg', 'sale'],
    flavor: 'menthol',
    color: 'Teal',
    inStock: true,
  },
  {
    id: 'eliquid-classic-tobacco-18mg',
    name: 'Vape Juice Classic Tobacco 18mg',
    description: 'Authentic tobacco flavor with strong 18mg nicotine.',
    price: 25.99,
    imageUrl: 'https://placehold.co/300x300/78716c/white?text=E-Liquid',
    categoryPath: ['e-liquid', 'eliquid-flavor', 'eliquid-tobacco', 'nicotine-strength', 'nic-18mg'],
    flavor: 'tobacco',
    color: 'Brown',
    inStock: true,
  },
  {
    id: 'eliquid-virginia-tobacco-12mg',
    name: 'Vape Juice Virginia Tobacco 12mg',
    description: 'Smooth Virginia tobacco with 12mg nicotine strength.',
    price: 25.99,
    imageUrl: 'https://placehold.co/300x300/78716c/white?text=E-Liquid',
    categoryPath: ['e-liquid', 'eliquid-flavor', 'eliquid-tobacco', 'nicotine-strength', 'nic-12mg'],
    flavor: 'tobacco',
    color: 'Tan',
    inStock: true,
  },

  // Accessories
  {
    id: 'usb-c-charger',
    name: 'USB-C Fast Charger',
    description: 'Fast charging USB-C cable for modern vape devices. 3ft length.',
    price: 12.99,
    imageUrl: 'https://placehold.co/300x300/3b82f6/white?text=Charger',
    categoryPath: ['accessories', 'chargers'],
    color: 'Black',
    inStock: true,
  },
  {
    id: 'wireless-charging-pad',
    name: 'Wireless Charging Pad',
    description: 'Qi-compatible wireless charging pad for supported vape devices.',
    price: 19.99,
    imageUrl: 'https://placehold.co/300x300/3b82f6/white?text=Charger',
    categoryPath: ['accessories', 'chargers', 'sale'],
    color: 'White',
    inStock: true,
  },
  {
    id: 'silicone-case-black',
    name: 'Silicone Protective Case - Black',
    description: 'Durable silicone case to protect your vape device. Fits most sizes.',
    price: 8.99,
    imageUrl: 'https://placehold.co/300x300/6366f1/white?text=Case',
    categoryPath: ['accessories', 'cases'],
    color: 'Black',
    inStock: true,
  },
  {
    id: 'leather-case-brown',
    name: 'Premium Leather Case - Brown',
    description: 'Premium leather carrying case with belt clip. Stylish protection.',
    price: 19.99,
    imageUrl: 'https://placehold.co/300x300/6366f1/white?text=Case',
    categoryPath: ['accessories', 'cases'],
    color: 'Brown',
    inStock: false,
  },
  {
    id: 'lanyard-black',
    name: 'Vape Lanyard - Black',
    description: 'Adjustable lanyard with quick-release clip. Keep your device handy.',
    price: 5.99,
    imageUrl: 'https://placehold.co/300x300/8b5cf6/white?text=Lanyard',
    categoryPath: ['accessories', 'lanyards'],
    color: 'Black',
    inStock: true,
  },
  {
    id: 'lanyard-rainbow',
    name: 'Vape Lanyard - Rainbow',
    description: 'Colorful rainbow lanyard with sturdy metal clip. Show your style.',
    price: 6.99,
    imageUrl: 'https://placehold.co/300x300/8b5cf6/white?text=Lanyard',
    categoryPath: ['accessories', 'lanyards'],
    color: 'Rainbow',
    inStock: true,
  },
  {
    id: 'replacement-cartridges-3pack',
    name: 'Replacement Cartridges 3-Pack',
    description: 'Pack of 3 replacement cartridges. Compatible with most pod systems.',
    price: 11.99,
    imageUrl: 'https://placehold.co/300x300/a855f7/white?text=Cartridge',
    categoryPath: ['accessories', 'cartridges', 'sale'],
    color: 'Clear',
    inStock: true,
  },
  {
    id: 'mesh-cartridge-5pack',
    name: 'Mesh Coil Cartridges 5-Pack',
    description: 'Advanced mesh coil cartridges for superior flavor. 5 pack.',
    price: 22.99,
    imageUrl: 'https://placehold.co/300x300/a855f7/white?text=Cartridge',
    categoryPath: ['accessories', 'cartridges'],
    color: 'Clear',
    inStock: true,
  },
  {
    id: 'carrying-pouch-teal',
    name: 'Zippered Carrying Pouch - Teal',
    description: 'Compact zippered pouch for storing device and accessories.',
    price: 9.99,
    imageUrl: 'https://placehold.co/300x300/6366f1/white?text=Case',
    categoryPath: ['accessories', 'cases'],
    color: 'Teal',
    inStock: true,
  },
];

// Helper function to filter products by category
export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter(product => product.categoryPath.includes(categoryId));
}
